-- begin TEAMTASKSPROJECT_PROJECT
create unique index IDX_TEAMTASKSPROJECT_PROJECT_UNIQ_NAME on TEAMTASKSPROJECT_PROJECT (NAME)^
-- end TEAMTASKSPROJECT_PROJECT
-- begin TEAMTASKSPROJECT_TASK_COMMENT
alter table TEAMTASKSPROJECT_TASK_COMMENT add constraint FK_TEAMTASKSPROJECT_TASK_COMMENT_ON_TASK foreign key (TASK_ID) references TEAMTASKSPROJECT_TASK(ID)^
alter table TEAMTASKSPROJECT_TASK_COMMENT add constraint FK_TEAMTASKSPROJECT_TASK_COMMENT_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_TEAMTASKSPROJECT_TASK_COMMENT_ON_TASK on TEAMTASKSPROJECT_TASK_COMMENT (TASK_ID)^
create index IDX_TEAMTASKSPROJECT_TASK_COMMENT_ON_AUTHOR on TEAMTASKSPROJECT_TASK_COMMENT (AUTHOR_ID)^
-- end TEAMTASKSPROJECT_TASK_COMMENT
-- begin TEAMTASKSPROJECT_TAG
create unique index IDX_TEAMTASKSPROJECT_TAG_UNIQ_NAME on TEAMTASKSPROJECT_TAG (NAME)^
-- end TEAMTASKSPROJECT_TAG
-- begin TEAMTASKSPROJECT_TASK
alter table TEAMTASKSPROJECT_TASK add constraint FK_TEAMTASKSPROJECT_TASK_ON_PROJECT foreign key (PROJECT_ID) references TEAMTASKSPROJECT_PROJECT(ID)^
alter table TEAMTASKSPROJECT_TASK add constraint FK_TEAMTASKSPROJECT_TASK_ON_ASSIGNEE foreign key (ASSIGNEE_ID) references SEC_USER(ID)^
create index IDX_TEAMTASKSPROJECT_TASK_ON_PROJECT on TEAMTASKSPROJECT_TASK (PROJECT_ID)^
create index IDX_TEAMTASKSPROJECT_TASK_ON_ASSIGNEE on TEAMTASKSPROJECT_TASK (ASSIGNEE_ID)^
-- end TEAMTASKSPROJECT_TASK
-- begin TEAMTASKSPROJECT_TASK_TEAMTASKSPROJECT_TAG_LINK
alter table TEAMTASKSPROJECT_TASK_TEAMTASKSPROJECT_TAG_LINK add constraint FK_TASTEATAG_ON_TASK foreign key (TASK_ID) references TEAMTASKSPROJECT_TASK(ID)^
alter table TEAMTASKSPROJECT_TASK_TEAMTASKSPROJECT_TAG_LINK add constraint FK_TASTEATAG_ON_TAG foreign key (TAG_ID) references TEAMTASKSPROJECT_TAG(ID)^
-- end TEAMTASKSPROJECT_TASK_TEAMTASKSPROJECT_TAG_LINK
