alter table TEAMTASKSPROJECT_TASK add constraint FK_TEAMTASKSPROJECT_TASK_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID);
create index IDX_TEAMTASKSPROJECT_TASK_ON_AUTHOR on TEAMTASKSPROJECT_TASK (AUTHOR_ID);
